name: "Test"

on:
  push:
    branches: [main*, develop]
    paths:
    - src/**
    - uv.lock
    - Makefile
    - pyproject.toml
    - .python-version
    - .github/workflows/test.yml
    - examples/1_introduction/**.py
    - examples/1_introduction/**.ipynb
    - examples/2_a_kedro_project/src/mlopus_kedro_example/*
  pull_request:
    branches: [main*, develop]
    paths:
    - src/**
    - uv.lock
    - Makefile
    - pyproject.toml
    - .python-version
    - .github/workflows/test.yml
    - examples/1_introduction/**.py
    - examples/1_introduction/**.ipynb
    - examples/2_a_kedro_project/src/mlopus_kedro_example/*

env:
  UV_CACHE_DIR: /tmp/.uv-cache

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: .python-version

    - name: Set up uv
      run: curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Cache UV
      uses: actions/cache@v3
      with:
        path: /tmp/.uv-cache
        key: uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
        restore-keys: |
          uv-${{ runner.os }}-${{ hashFiles('uv.lock') }}
          uv-${{ runner.os }}

    - name: Install
      run: |
        make install-project install-tools
        sudo -v ; curl https://rclone.org/install.sh | sudo bash

    - name: Test
      run: make test

    - name: Publish coverage report to GitHub Pages
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: htmlcov
        target-folder: coverage
